#!/usr/bin/env python

import os
import sys
import argparse
import glob
import json

ROOT = os.path.dirname(os.path.abspath(__file__))

def get_args():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="subcommand")
    format_command = subparsers.add_parser("format", description="Format services.")
    format_command = subparsers.add_parser("validate", description="Validate services.")
    return parser.parse_args()

def get_service_filenames(root):
    filenames = []
    for item in glob.glob(os.path.join(root, "*")):
        if os.path.isdir(item):
            filenames += get_service_filenames(item)
        elif os.path.isfile(item):
            if os.path.basename(item) == "service.json":
                filenames.append(item)
    return filenames

def format(args):
    for fn in get_service_filenames(ROOT):
        with open(fn, 'r') as f:
            data = json.load(f)
        with open(fn, 'w') as f:
            json.dump(data, f, indent=4, sort_keys=True, separators=(',', ': '))

def validate(args):
    failed = []
    for fn in get_service_filenames(ROOT):
        with open(fn, 'r') as f:
            data = f.read()
        try:
            j = json.loads(data)
            if data != json.dumps(j, indent=4, sort_keys=True, separators=(',', ': ')):
                failed.append(fn)
        except ValueError:
            failed.append(fn)
    if len(failed) != 0:
        print "The following services are not formatted correctly:"
        for f in failed:
            print f
        sys.exit(1)

def main():
    args = get_args()
    if args.subcommand == "format":
        format(args)
    elif args.subcommand == "validate":
        validate(args)
    
if __name__ == "__main__":
    main()