##############################################################################
#
# Copyright (C) Zenoss, Inc. 2020, all rights reserved.
#
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
#
##############################################################################
from __future__ import print_function

__doc__ = '''
Add global.conf built by serviced to mariadb services
to have actual config instead of default
'''

import servicemigration as sm

version = "6.5.0"


def migrate(ctx, *args, **kw):
    updated = False
    global_conf = sm.ConfigFile(
        name="/opt/zenoss/etc/global.conf",
        filename="/opt/zenoss/etc/global.conf",
        owner="zenoss:zenoss",
        permissions="660",
        content="# Generated by serviced\n{{range $k,$v:=contextFilter . \"global.conf.\"}}{{$k}} {{$v}}\n{{end}}"
    )

    mariadbs = filter(lambda s: s.name in ["mariadb-model", "mariadb-events", "mariadb"], ctx.services)
    for svc in mariadbs:
        if not [cfg for cfg in svc.originalConfigs if cfg.name == global_conf.name]:
            svc.originalConfigs.append(global_conf)
            updated = True
            print("Updated %s service" % svc.name)

        if not [cfg for cfg in svc.configFiles if cfg.name == global_conf.name]:
            svc.configFiles.append(global_conf)
            updated = True
            print("Updated %s service" % svc.name)

    return updated
