FROM zenoss/zenoss-centos-base:%VERSION%.devtools

RUN yum makecache && \
	yum install -y ruby ruby-devel && \
	yum autoremove -y && \
	yum clean all && \
	gem install --no-ri --no-rdoc ffi:1.11.3 fpm:1.11.0

RUN pip install -U setuptools

RUN groupadd --gid %GID% builder
RUN useradd --uid %UID% --gid %GID% --comment "" builder
