FROM ubuntu:bionic

RUN apt-get update -qq && \
    apt-get install -y -q \
    build-essential \
    libtool \
    rpm \
    curl \
    make \
    autoconf \
    ruby \
    ruby-dev \
    python-wheel \
    python-setuptools \
    libdevmapper-dev


RUN groupadd --gid %GID% builder
RUN useradd --uid %UID% --gid %GID% --comment "" builder
